spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://127.0.0.1:3305/spring_batch?characterEncoding=UTF-8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root1
      password: echo5018
  batch:
    initialize-schema: never